### ISSUE TITLE
Outdated php version

### ISSUE THREAD

**Issue by ChristianGiupponi** [finc/docker-vufind2#2]
Hi,
I have tried to install your container but I get a lot of errors due to:

```
Problem 1
    - This package requires php >=5.6 but your PHP version (5.4.45) does not satisfy that requirement.
```

Can you update the php version?

**Comment by useltmann** [comment]
Please specify the image-tag `php_5.6` or `php_5.6-1` or even `php_7.0` or `php_7.0-1` instead of `latest` to get the updated php-version you require. you can find a complete list of image-tags here https://hub.docker.com/r/ubleipzig/vufind2/tags/ 

The tag `latest` always points to what vufind at least requires. As for now this is php 5.4 and will change to php 5.6 as soon as vufind 4 will be released which might be in april.

**Comment by ChristianGiupponi** [comment]
Thanks, how should I specify it?
